# Generated by Django 3.0.4 on 2020-03-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_trans',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_trans',
            field=models.DateField(null=True),
        ),
    ]
