# Generated by Django 3.0.4 on 2020-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
