# Generated by Django 3.0.4 on 2020-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.TextField(unique=True),
        ),
    ]
