# Generated by Django 3.0.4 on 2020-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200421_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_name', 'username')},
        ),
    ]
