# Generated by Django 3.0.4 on 2020-04-16 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('other', models.CharField(blank=True, max_length=100)),
                ('direction', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('amount_accnt', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Account')),
            ],
        ),
    ]
