# Generated by Django 3.0.4 on 2020-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_accnt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
